services:
  postgres:
    image: postgres:17.5-bullseye
    restart: always
    container_name: supermarket_db
    ports:
      - "5432:5432"
    environment: # 👈 Usa el archivo .env
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Si tienes un servicio para tu aplicación Spring Boot, añádelo así:
  #app:
    #image: tu-imagen-spring-boot
    #restart: always
    #ports:
      #- "8080:8080"
    #env_file:
      #- .env
    #depends_on:
      #- postgres

volumes:
  postgres_data: